name:                 promt
version:              0.1.0.0
visibility:           public
id:                   promt-0.1.0.0-inplace
key:                  promt-0.1.0.0-inplace
license:              MIT
copyright:            2026 Promt/ProSe contributors
maintainer:           Promt/ProSe contributors
synopsis:
    Graph-based type inference and checking for PROMT processes.

description:
    Infers recursive local types for probabilistic multiparty
    processes, checks type specifications, and exports to ProSe.

category:             Language
abi:                  inplace
exposed:              True
exposed-modules:
    Frontend.Parser Output.Context Syntax.Process Typing.Check
    Typing.Inference Typing.Relations Typing.Types

hidden-modules:
    Syntax.Binder Syntax.WellFormed Typing.Expressions
    Typing.Inference.Candidate Typing.Inference.Construct
    Typing.Inference.Source Typing.Relations.Graph
    Typing.Relations.Matching

import-dirs:
    /Users/alenge/Documents/ARTIFACT/prose/promt/dist-newstyle/build/aarch64-osx/ghc-9.6.7/promt-0.1.0.0/build

library-dirs:
    /Users/alenge/Documents/ARTIFACT/prose/promt/dist-newstyle/build/aarch64-osx/ghc-9.6.7/promt-0.1.0.0/build

library-dirs-static:
    /Users/alenge/Documents/ARTIFACT/prose/promt/dist-newstyle/build/aarch64-osx/ghc-9.6.7/promt-0.1.0.0/build

dynamic-library-dirs:
    /Users/alenge/Documents/ARTIFACT/prose/promt/dist-newstyle/build/aarch64-osx/ghc-9.6.7/promt-0.1.0.0/build

data-dir:             /Users/alenge/Documents/ARTIFACT/prose/promt/.
hs-libraries:         HSpromt-0.1.0.0-inplace
depends:              base-4.18.3.0 containers-0.6.7
haddock-interfaces:
    /Users/alenge/Documents/ARTIFACT/prose/promt/dist-newstyle/build/aarch64-osx/ghc-9.6.7/promt-0.1.0.0/doc/html/promt/promt.haddock

haddock-html:
    /Users/alenge/Documents/ARTIFACT/prose/promt/dist-newstyle/build/aarch64-osx/ghc-9.6.7/promt-0.1.0.0/doc/html/promt
